export const SPECIALTIES_SEED = [
  {
    code: 'ophthalmology',
    name: 'Ophtalmologie',
    description: 'Médecine des yeux et troubles visuels',
    icon: 'eye',
  },
  {
    code: 'cardiology',
    name: 'Cardiologie',
    description: 'Médecine du cœur et système vasculaire',
    icon: 'heart',
  },
  {
    code: 'dermatology',
    name: 'Dermatologie',
    description: 'Médecine de la peau',
    icon: 'skin',
  },
  {
    code: 'general-medicine',
    name: 'Médecine Générale',
    description: 'Médecine généraliste',
    icon: 'stethoscope',
  },
  {
    code: 'gynecology',
    name: 'Gynécologie',
    description: 'Médecine des femmes et obstétrique',
    icon: 'female',
  },
  {
    code: 'pediatrics',
    name: 'Pédiatrie',
    description: 'Médecine des enfants',
    icon: 'baby',
  },
  {
    code: 'neurology',
    name: 'Neurologie',
    description: 'Médecine du système nerveux',
    icon: 'brain',
  },
  {
    code: 'orthopedics',
    name: 'Orthopédie',
    description: 'Médecine des os et articulations',
    icon: 'bone',
  },
  {
    code: 'psychiatry',
    name: 'Psychiatrie',
    description: 'Médecine mentale et comportement',
    icon: 'mind',
  },
  {
    code: 'radiology',
    name: 'Radiologie',
    description: 'Imagerie médicale',
    icon: 'xray',
  },
  {
    code: 'urology',
    name: 'Urologie',
    description: 'Médecine du système urinaire',
    icon: 'urine',
  },
  {
    code: 'gastroenterology',
    name: 'Gastro-entérologie',
    description: 'Médecine du système digestif',
    icon: 'stomach',
  },
  {
    code: 'ent',
    name: 'ORL (Oto-rhino-laryngologie)',
    description: 'Médecine de l\'oreille, nez et gorge',
    icon: 'ear',
  },
  {
    code: 'pneumology',
    name: 'Pneumologie',
    description: 'Médecine des poumons et voies respiratoires',
    icon: 'lungs',
  },
  {
    code: 'rheumatology',
    name: 'Rhumatologie',
    description: 'Médecine des rhumatismes et maladies articulaires',
    icon: 'joints',
  },
  {
    code: 'endocrinology',
    name: 'Endocrinologie',
    description: 'Médecine des hormones et glandes endocrines',
    icon: 'hormones',
  },
  {
    code: 'oncology',
    name: 'Oncologie',
    description: 'Médecine du cancer',
    icon: 'cancer',
  },
  {
    code: 'surgery',
    name: 'Chirurgie Générale',
    description: 'Chirurgie générale',
    icon: 'surgery',
  },
];
